version: '3.1'
services:
  db:
    image: mariadb:10
    container_name: goyo_db
    environment:
      TZ: Asia/Seoul
      MYSQL_DATABASE: ${DATABASE_DB}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASS}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASS}
    volumes:
      - /var/db/docker/mariadb/goyo/data:/data/db
    ports:
      - 3306:3306
  redis:
    image: redis:latest
    container_name: goyo_redis
    command: redis-server --port 6379
    hostname: redis_server
    ports:
      - 6379:6379