name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        proxy_host: ${{ secrets.HOST }}
        proxy_username: ${{ secrets.USERNAME }}
        proxy_password: ${{ secrets.PASSWORD }}
        proxy_port: ${{ secrets.PORT }}
        script: whoami