  name: CI
  on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
  jobs:
    access_test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: sshPass install
        run : sudo apt-get install -y sshpass
      - name: access Server
        shell: bash
        run: ${{ secrets.ACCESS_TEST }}